export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const GET_ARTICLE = 'GET_ARTICLE';
export const FAILED_ARTICLE_CREATION = 'FAILED_ARTICLE_CREATION';
export const FAILED_ARTICLE_UPDATE = 'FAILED_ARTICLE_UPDATE';
export const GET_FEED = 'GET_FEED';
