export const BOOKMARK_ARTICLE_START = 'BOOKMARK_ARTICLE_START';
export const BOOKMARK_ARTICLE_END = 'BOOKMARK_ARTICLE_END';
export const BOOKMARK_ARTICLE_SUCCESS = 'BOOKMARK_ARTICLE_SUCCESS';
export const BOOKMARK_ARTICLE_FAILURE = 'BOOKMARK_ARTICLE_FAILURE';
export const BOOKMARK_GET_ALL = 'BOOKMARK_GET_ALL';
export const BOOKMARK_GET_ALL_FAIL = 'BOOKMARK_GET_ALL_FAIL';
