export const GET_BOOKMARK_ARTICLE_SUCCESS = 'GET_BOOKMARK_ARTICLE_SUCCESS';
export const GET_BOOKMARK_ARTICLE_FAILURE = 'GET_BOOKMARK_ARTICLE_FAILURE';
export const DELETE_BOOKMARK_ARTICLE_SUCCESS = 'DELETE_BOOKMARK_ARTICLE_SUCCESS';
export const DELETE_BOOKMARK_ARTICLE_FAILURE = 'DELETE_BOOKMARK_ARTICLE_FAILURE';
