export const SET_COMMENT_SUCCESS = 'SET_COMMENT_SUCCESS';
export const SET_COMMENT_ERROR = 'SET_COMMENT_ERROR';
export const GET_COMMENTS = 'GET_COMMENTS';
export const SET_COMMENT_DELETE = 'SET_COMMENT_DELETE';
