export const RATE_ARTICLE_START = 'RATE_ARTICLE_START';
export const RATE_ARTICLE_SUCCESS = 'RATE_ARTICLE_SUCCESS';
export const RATE_ARTICLE_FAILURE = 'RATE_ARTICLE_FAILURE';
export const GET_RATING = 'GET_RATING';
